name: safelight
description: A new Flutter project.
publish_to: 'none'
# ios
version: 1.2.2+7

# android
# version: 1.1.0+3
environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  http: ^0.13.5
  flutter_local_notifications: ^9.7.0
  flutter_screenutil: ^5.5.4
  firebase_core: ^1.22.0
  firebase_auth: ^3.9.0
  permission_handler: ^10.0.2
  flutter_native_splash: ^2.2.10+1
  flutter_blue_plus: ^1.3.1
  shimmer: ^2.0.0
  geolocator: ^9.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  torch_light: ^1.0.0
  flutter_compass: ^0.7.0
  cloud_firestore: ^3.5.1
  latlong2: ^0.8.1
  auto_size_text: ^3.0.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  bloc: ^8.1.0
  flutter_tts: ^3.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/images/ic/

flutter_native_splash:
  color: "#758BFD"
  image: lib/assets/images/ic/ic_logo.png
  branding: lib/assets/images/ic/ic_copyright.png
  branding_mode: bottom
  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png
  #branding_dark: assets/dart_dark.png
  android_12:
    color: "#758BFD"
    image: lib/assets/images/ic/ic_logo_android.png
    #color: "#42a5f5"
    #icon_background_color: "#111111"
    #branding: assets/dart.png
    #image_dark: assets/android12splash-invert.png
    #color_dark: "#042a49"
    #icon_background_color_dark: "#eeeeee"
  web: false
  #fullscreen: true