// ignore_for_file: constant_identifier_names

enum ServiceType {
  SEARCH_BY_DIRECTION_OF_VIEW,
  CONNECT_ALL_IMMEDIATELY_AFTER_SEARCH,
  SEARCH_FOR_NEARBY,
  CONNECT_IMMEDIATELY_AFTER_SEARCH_FOR_NEARBY,
}
